/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Aggregate Project */
        post: operations["queue_aggregate_project_api_v1_projects__project_id__aggregate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/summary/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Generate Project Summary */
        post: operations["queue_generate_project_summary_api_v1_projects__project_id__summary_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/aggregation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Aggregation */
        get: operations["get_project_aggregation_api_v1_projects__project_id__aggregation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources/text/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Text Source */
        post: operations["upload_text_source_api_v1_projects__project_id__sources_text_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources/audio/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Audio Source */
        post: operations["upload_audio_source_api_v1_projects__project_id__sources_audio_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources/text/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Raw Text Note */
        post: operations["create_raw_text_note_api_v1_projects__project_id__sources_text_raw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Sources */
        get: operations["list_project_sources_api_v1_projects__project_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/documents/{source_document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Document */
        get: operations["get_source_document_api_v1_sources_documents__source_document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/audios/{source_audio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Audio */
        get: operations["get_source_audio_api_v1_sources_audios__source_audio_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/audios/{source_audio_id}/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Transcribe Audio */
        post: operations["queue_transcribe_audio_api_v1_sources_audios__source_audio_id__transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/documents/{source_document_id}/chunk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Chunk Document */
        post: operations["queue_chunk_document_api_v1_sources_documents__source_document_id__chunk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/documents/{source_document_id}/chunk/semantic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Chunk Document Semantic */
        post: operations["queue_chunk_document_semantic_api_v1_sources_documents__source_document_id__chunk_semantic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/documents/{source_document_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Extract Document */
        post: operations["queue_extract_document_api_v1_sources_documents__source_document_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Entities */
        get: operations["list_project_entities_api_v1_projects__project_id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Summary */
        get: operations["get_project_summary_api_v1_projects__project_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transcripts/{transcript_id}/chunk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Chunk Transcript */
        post: operations["queue_chunk_transcript_api_v1_transcripts__transcript_id__chunk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transcripts/{transcript_id}/chunk/semantic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Chunk Transcript Semantic */
        post: operations["queue_chunk_transcript_semantic_api_v1_transcripts__transcript_id__chunk_semantic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transcripts/{transcript_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Extract Transcript */
        post: operations["queue_extract_transcript_api_v1_transcripts__transcript_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Text */
        post: operations["ingest_text_api_v1_materials_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Audio */
        post: operations["ingest_audio_api_v1_materials_audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Materials */
        get: operations["list_materials_api_v1_materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material */
        get: operations["get_material_api_v1_materials__material_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{material_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess Material */
        post: operations["reprocess_material_api_v1_materials__material_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Insights */
        get: operations["list_insights_api_v1_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/aggregates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Aggregates */
        get: operations["list_aggregates_api_v1_dashboard_aggregates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/aggregates/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute Aggregates */
        post: operations["recompute_aggregates_api_v1_dashboard_aggregates_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AudioSourceListItem */
        AudioSourceListItem: {
            /**
             * Source Kind
             * @default audio
             * @constant
             */
            source_kind: "audio";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string | null;
            /** Language */
            language: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_ingest_audio_api_v1_materials_audio_post */
        Body_ingest_audio_api_v1_materials_audio_post: {
            /** File */
            file: string;
            /** Title */
            title?: string | null;
            /** Source Uri */
            source_uri?: string | null;
            /** Extra Metadata */
            extra_metadata?: string | null;
        };
        /** Body_upload_audio_source_api_v1_projects__project_id__sources_audio_upload_post */
        Body_upload_audio_source_api_v1_projects__project_id__sources_audio_upload_post: {
            /** File */
            file: string;
            /** Language */
            language?: string | null;
            /** @default upload */
            source_type: components["schemas"]["SourceType"];
        };
        /** Body_upload_text_source_api_v1_projects__project_id__sources_text_upload_post */
        Body_upload_text_source_api_v1_projects__project_id__sources_text_upload_post: {
            /** File */
            file: string;
            /** @default upload */
            source_type: components["schemas"]["SourceType"];
        };
        /**
         * DashboardAggregateKind
         * @enum {string}
         */
        DashboardAggregateKind: "material_counts" | "insight_counts" | "entity_frequency" | "pipeline_health";
        /** DashboardAggregateRead */
        DashboardAggregateRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["DashboardAggregateKind"];
            /** Period Key */
            period_key: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
        };
        /** DocumentSourceListItem */
        DocumentSourceListItem: {
            /**
             * Source Kind
             * @default document
             * @constant
             */
            source_kind: "document";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string | null;
            source_type: components["schemas"]["SourceType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EntityListResponse */
        EntityListResponse: {
            /** Items */
            items: components["schemas"]["ExtractedEntityRead"][];
            meta: components["schemas"]["PaginatedMeta"];
        };
        /**
         * EntityType
         * @description Type of extracted research entity.
         * @enum {string}
         */
        EntityType: "person" | "organization" | "location" | "date" | "topic" | "claim" | "metric" | "hypothesis" | "risk" | "opportunity" | "reference" | "custom";
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string | {
                [key: string]: unknown;
            } | unknown[];
        };
        /** ExtractedEntityRead */
        ExtractedEntityRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Source Document Id */
            source_document_id: string | null;
            /** Source Audio Id */
            source_audio_id: string | null;
            /** Transcript Id */
            transcript_id: string | null;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            entity_type: components["schemas"]["EntityType"];
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Confidence Score */
            confidence_score: number | null;
            /** Tags Json */
            tags_json: {
                [key: string]: unknown;
            } | unknown[];
            /** Evidence Json */
            evidence_json: {
                [key: string]: unknown;
            } | unknown[];
            /** Canonical Entity Id */
            canonical_entity_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Pr Implication */
            pr_implication?: string | null;
            /** Messaging Guidance */
            messaging_guidance?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @example ok
             */
            status: string;
            /** App */
            app: string;
            /** Environment */
            environment: string;
        };
        /** InsightRead */
        InsightRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Headline */
            headline: string;
            /** Summary */
            summary: string | null;
            /** Body */
            body: string | null;
            /** Confidence */
            confidence: number | null;
            /** Dedup Key */
            dedup_key: string;
            /** Canonical Insight Id */
            canonical_insight_id: string | null;
            /** Embedding Model */
            embedding_model: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Source Links */
            source_links?: components["schemas"]["InsightSourceLinkRead"][];
        };
        /** InsightSourceLinkRead */
        InsightSourceLinkRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Span Start */
            span_start: number | null;
            /** Span End */
            span_end: number | null;
            /** Quote */
            quote: string | null;
            /** Locator */
            locator: {
                [key: string]: unknown;
            };
        };
        /**
         * JobStatus
         * @description Async job / pipeline lifecycle (e.g. transcription).
         * @enum {string}
         */
        JobStatus: "pending" | "queued" | "running" | "completed" | "failed" | "cancelled";
        /** MaterialCreate */
        MaterialCreate: {
            /** Title */
            title?: string | null;
            /** Source Uri */
            source_uri?: string | null;
            /** Mime Type */
            mime_type?: string | null;
            /** Extra Metadata */
            extra_metadata?: {
                [key: string]: unknown;
            };
            material_type: components["schemas"]["MaterialType"];
            /** Raw Text */
            raw_text?: string | null;
            /**
             * Audio Filename
             * @description Original filename hint when uploading audio (storage key set server-side).
             */
            audio_filename?: string | null;
        };
        /** MaterialRead */
        MaterialRead: {
            /** Title */
            title?: string | null;
            /** Source Uri */
            source_uri?: string | null;
            /** Mime Type */
            mime_type?: string | null;
            /** Extra Metadata */
            extra_metadata?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            material_type: components["schemas"]["MaterialType"];
            status: components["schemas"]["ProcessingStatus"];
            /** Raw Text */
            raw_text: string | null;
            /** Normalized Text */
            normalized_text: string | null;
            /** Audio Storage Key */
            audio_storage_key: string | null;
            /** Processing Error */
            processing_error: string | null;
            /** Parent Material Id */
            parent_material_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MaterialType
         * @enum {string}
         */
        MaterialType: "text" | "audio";
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** PaginatedMeta */
        PaginatedMeta: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ProcessingStatus
         * @enum {string}
         */
        ProcessingStatus: "pending" | "transcribing" | "normalizing" | "extracting" | "deduplicating" | "aggregating" | "completed" | "failed";
        /** ProcessingTaskQueued */
        ProcessingTaskQueued: {
            /**
             * Task Id
             * @description Celery task id
             */
            task_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /** Items */
            items: components["schemas"]["ProjectRead"][];
            meta: components["schemas"]["PaginatedMeta"];
        };
        /** ProjectRead */
        ProjectRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RawTextNoteCreate */
        RawTextNoteCreate: {
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
        };
        /** ResearchAggregationSnapshotRead */
        ResearchAggregationSnapshotRead: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Snapshot Type */
            snapshot_type: string;
            /** Period Key */
            period_key: string;
            /** Payload Json */
            payload_json: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ResearchAggregationSnapshotResponse */
        ResearchAggregationSnapshotResponse: {
            /** @description Null if aggregate has not been run for this project. */
            snapshot?: components["schemas"]["ResearchAggregationSnapshotRead"] | null;
        };
        /** ResearchSummaryRead */
        ResearchSummaryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            status: components["schemas"]["SummaryStatus"];
            /** Summary Text */
            summary_text: string;
            /** Key Findings Json */
            key_findings_json: unknown[] | {
                [key: string]: unknown;
            };
            /** Facts Json */
            facts_json: unknown[] | {
                [key: string]: unknown;
            };
            /** Hypotheses Json */
            hypotheses_json: unknown[] | {
                [key: string]: unknown;
            };
            /** Risks Json */
            risks_json: unknown[] | {
                [key: string]: unknown;
            };
            /** Opportunities Json */
            opportunities_json: unknown[] | {
                [key: string]: unknown;
            };
            /** Recommendations Json */
            recommendations_json: unknown[] | {
                [key: string]: unknown;
            };
            /** Open Questions Json */
            open_questions_json: unknown[] | {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SourceAudioDetailRead */
        SourceAudioDetailRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Filename */
            filename: string;
            /** Original Path */
            original_path: string | null;
            /** Mime Type */
            mime_type: string | null;
            /** Duration Seconds */
            duration_seconds: string | null;
            /** Language */
            language: string | null;
            /** Metadata Json */
            metadata_json: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            transcript?: components["schemas"]["TranscriptRead"] | null;
            /**
             * Transcript Segments Count
             * @default 0
             */
            transcript_segments_count: number;
            /** Transcript Segments Sample */
            transcript_segments_sample?: components["schemas"]["TranscriptSegmentRead"][];
            /**
             * Text Chunks Count
             * @default 0
             */
            text_chunks_count: number;
            /**
             * Extracted Entities Count
             * @default 0
             */
            extracted_entities_count: number;
        };
        /** SourceAudioRead */
        SourceAudioRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Filename */
            filename: string;
            /** Original Path */
            original_path: string | null;
            /** Mime Type */
            mime_type: string | null;
            /** Duration Seconds */
            duration_seconds: string | null;
            /** Language */
            language: string | null;
            /** Metadata Json */
            metadata_json: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SourceDocumentDetailRead */
        SourceDocumentDetailRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Filename */
            filename: string;
            /** Original Path */
            original_path: string | null;
            /** Mime Type */
            mime_type: string | null;
            source_type: components["schemas"]["SourceType"];
            /** Raw Text */
            raw_text: string | null;
            /** Metadata Json */
            metadata_json: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Transcript */
            transcript?: null;
            /**
             * Transcript Segments Count
             * @default 0
             */
            transcript_segments_count: number;
            /**
             * Text Chunks Count
             * @default 0
             */
            text_chunks_count: number;
            /**
             * Extracted Entities Count
             * @default 0
             */
            extracted_entities_count: number;
        };
        /** SourceDocumentRead */
        SourceDocumentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Filename */
            filename: string;
            /** Original Path */
            original_path: string | null;
            /** Mime Type */
            mime_type: string | null;
            source_type: components["schemas"]["SourceType"];
            /** Raw Text */
            raw_text: string | null;
            /** Metadata Json */
            metadata_json: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SourceType
         * @description How the source was obtained or classified.
         * @enum {string}
         */
        SourceType: "upload" | "url" | "api" | "manual" | "import" | "other";
        /**
         * SummaryStatus
         * @description Research summary generation state.
         * @enum {string}
         */
        SummaryStatus: "draft" | "generating" | "ready" | "stale" | "failed";
        /** TranscriptRead */
        TranscriptRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Audio Id
             * Format: uuid
             */
            source_audio_id: string;
            /** Full Text */
            full_text: string;
            /** Language */
            language: string | null;
            status: components["schemas"]["JobStatus"];
            /** Provider Name */
            provider_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Extracted Entities Count
             * @default 0
             */
            extracted_entities_count: number;
        };
        /** TranscriptSegmentRead */
        TranscriptSegmentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transcript Id
             * Format: uuid
             */
            transcript_id: string;
            /** Speaker Label */
            speaker_label: string | null;
            /** Start Seconds */
            start_seconds: string;
            /** End Seconds */
            end_seconds: string;
            /** Text */
            text: string;
            /** Confidence Score */
            confidence_score: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UnifiedSourcesResponse */
        UnifiedSourcesResponse: {
            /** Items */
            items: (components["schemas"]["DocumentSourceListItem"] | components["schemas"]["AudioSourceListItem"])[];
            meta: components["schemas"]["PaginatedMeta"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | boolean;
                    };
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                /** @description Page size */
                limit?: number;
                /** @description Offset */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    queue_aggregate_project_api_v1_projects__project_id__aggregate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingTaskQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_generate_project_summary_api_v1_projects__project_id__summary_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingTaskQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_aggregation_api_v1_projects__project_id__aggregation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchAggregationSnapshotResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_text_source_api_v1_projects__project_id__sources_text_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_text_source_api_v1_projects__project_id__sources_text_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_audio_source_api_v1_projects__project_id__sources_audio_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_audio_source_api_v1_projects__project_id__sources_audio_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAudioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_raw_text_note_api_v1_projects__project_id__sources_text_raw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RawTextNoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_sources_api_v1_projects__project_id__sources_get: {
        parameters: {
            query?: {
                /** @description Page size */
                limit?: number;
                /** @description Offset */
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedSourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_document_api_v1_sources_documents__source_document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentDetailRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_audio_api_v1_sources_audios__source_audio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_audio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAudioDetailRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_transcribe_audio_api_v1_sources_audios__source_audio_id__transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_audio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingTaskQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_chunk_document_api_v1_sources_documents__source_document_id__chunk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingTaskQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_chunk_document_semantic_api_v1_sources_documents__source_document_id__chunk_semantic_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingTaskQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_extract_document_api_v1_sources_documents__source_document_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingTaskQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_entities_api_v1_projects__project_id__entities_get: {
        parameters: {
            query?: {
                entity_type?: components["schemas"]["EntityType"] | null;
                min_confidence?: number | null;
                source_document_id?: string | null;
                source_audio_id?: string | null;
                transcript_id?: string | null;
                /** @description Include types excluded by default (e.g. supporting_fact) */
                include_all_types?: boolean | null;
                /** @description Page size */
                limit?: number;
                /** @description Offset */
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityListResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_summary_api_v1_projects__project_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSummaryRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_chunk_transcript_api_v1_transcripts__transcript_id__chunk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingTaskQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_chunk_transcript_semantic_api_v1_transcripts__transcript_id__chunk_semantic_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingTaskQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_extract_transcript_api_v1_transcripts__transcript_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingTaskQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_text_api_v1_materials_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_audio_api_v1_materials_audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_audio_api_v1_materials_audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_materials_api_v1_materials_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_api_v1_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_material_api_v1_materials__material_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_insights_api_v1_insights_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_aggregates_api_v1_dashboard_aggregates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardAggregateRead"][];
                };
            };
        };
    };
    recompute_aggregates_api_v1_dashboard_aggregates_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
}
